// lib/pveCheck/rubric.ts — Deterministic rubric (de canon)
// Versie wordt gebumpt na review-feedback patronen.
import type { PveRubric, PveRubricItem } from "@/types/pveCheck";
import { RUBRIC_VERSION } from "@/types/pveCheck";

// ============================================================================
// RUBRIC ITEMS — per veld: severity, fixEffort, quality criteria, risk overlay,
// pitfalls, en een gratis voorbeeldtekst (template, niet LLM).
// ============================================================================

const ITEMS: PveRubricItem[] = [
  // ── BASIS ─────────────────────────────────────────────────────────────────
  {
    id: "basis.projectType",
    chapter: "basis",
    fieldId: "projectType",
    label: "Projecttype",
    severity: "critical",
    fixEffort: "XS",
    weight: 12,
    keywords: ["nieuwbouw", "verbouwing", "bijgebouw", "renovatie", "aanbouw", "uitbouw"],
    qualityCriteria: "Eenduidig projecttype benoemd (nieuwbouw/verbouwing/bijgebouw/hybride).",
    riskOverlay: "Zonder duidelijk projecttype worden vergunning, budget en planning verkeerd ingeschat.",
    pitfalls: ["'Verbouwing' en 'renovatie' worden verwisseld", "Hybride scope niet gedefinieerd"],
    exampleGood: "Het project betreft een verbouwing van een bestaande jaren-30 woning met uitbouw aan de achterzijde.",
  },
  {
    id: "basis.locatie",
    chapter: "basis",
    fieldId: "locatie",
    label: "Locatie",
    severity: "critical",
    fixEffort: "XS",
    weight: 8,
    keywords: ["locatie", "adres", "gemeente", "wijk", "stad", "straat", "perceel"],
    qualityCriteria: "Minimaal gemeente + straat of kadastrale aanduiding.",
    riskOverlay: "Locatie bepaalt bestemmingsplan, bodemgesteldheid en bouwvoorschriften.",
    pitfalls: ["Alleen 'regio' zonder specifiek adres", "Postcode ontbreekt"],
    exampleGood: "Het project bevindt zich aan de Kerkstraat 12, 3511 CX Utrecht.",
  },
  {
    id: "basis.bouwjaar",
    chapter: "basis",
    fieldId: "bouwjaar",
    label: "Bouwjaar (bij verbouwing)",
    severity: "important",
    fixEffort: "XS",
    weight: 4,
    keywords: ["bouwjaar", "jaar", "gebouwd", "oorsprong", "bestaand"],
    qualityCriteria: "Specifiek bouwjaar of decade benoemd.",
    riskOverlay: "Bouwjaar bepaalt constructieve aannames, asbest-risico en energielabel-potentieel.",
    pitfalls: ["'Oud huis' zonder jaartal", "Bouwjaar verward met aankoopdatum"],
    exampleGood: "De woning is gebouwd in 1932 en heeft een gemetselde spouwmuur zonder isolatie.",
  },
  {
    id: "basis.gebruikersProfiel",
    chapter: "basis",
    fieldId: "gebruikersProfiel",
    label: "Gebruikersprofiel",
    severity: "important",
    fixEffort: "XS",
    weight: 5,
    keywords: ["bewoner", "gezin", "senior", "thuiswerken", "kinderen", "ouderen", "mensen", "gebruiker", "bewoning"],
    qualityCriteria: "Huishoudsamenstelling en bijzondere gebruikerseisen (mobiliteit, thuiswerken, leeftijd) benoemd.",
    riskOverlay: "Zonder gebruikersprofiel worden levensloopbestendigheid en werkplekeisen niet meegenomen.",
    pitfalls: ["Alleen 'gezin' zonder leeftijden of behoeften", "Thuiswerkvraag overgeslagen", "Mobiliteitsbeperkingen niet vermeld"],
    exampleGood: "Bewoners: gezin met 2 kinderen (6 en 10 jaar) + 1 thuiswerker. Eis: aparte werkkamer, drempelvrije begane grond.",
  },
  {
    id: "basis.omgevingsContext",
    chapter: "basis",
    fieldId: "omgevingsContext",
    label: "Omgevingscontext",
    severity: "important",
    fixEffort: "XS",
    weight: 4,
    keywords: ["monument", "beschermd", "welstand", "buren", "bestemmingsplan", "stedenbouw", "erfgoed", "woonwijk"],
    qualityCriteria: "Ligging (stedelijk/landelijk), welstandsregime en eventuele monumentale status benoemd.",
    riskOverlay: "Monumentale of beschermde status beperkt ontwerpvrijheid en verlengt vergunningsproces.",
    pitfalls: ["Beschermd stadsgezicht niet gecheckt", "Welstandscommissie over het hoofd gezien"],
    exampleGood: "Pand ligt in beschermd stadsgezicht (welstandsklasse zwaar). Gevelwijzigingen vereisen vooroverleg.",
  },

  // ── RUIMTES ───────────────────────────────────────────────────────────────
  {
    id: "ruimtes.rooms",
    chapter: "ruimtes",
    fieldId: "rooms",
    label: "Ruimteprogramma",
    severity: "critical",
    fixEffort: "M",
    weight: 16,
    keywords: ["slaapkamer", "badkamer", "woonkamer", "keuken", "kamer", "ruimte", "m2", "m²", "oppervlakte"],
    qualityCriteria: "Minimaal hoofd-ruimtes benoemd met gewenst oppervlak of verhouding.",
    riskOverlay: "Zonder ruimteprogramma is geen plattegrond of kostenverdeling mogelijk.",
    pitfalls: ["Alleen 'woonkamer' zonder andere ruimtes", "Oppervlaktes ontbreken", "Berging/bijkeuken vergeten"],
    exampleGood: "Woonkamer (ca. 45m²), open keuken (20m²), 3 slaapkamers (12-15m²), badkamer (8m²), toilet, berging (6m²).",
  },
  {
    id: "ruimtes.daglicht",
    chapter: "ruimtes",
    fieldId: "daglicht",
    label: "Daglicht en oriëntatie",
    severity: "important",
    fixEffort: "S",
    weight: 6,
    keywords: ["daglicht", "zonlicht", "raam", "glas", "oriëntatie", "zon", "uitzicht", "noord", "zuid", "west", "oost"],
    qualityCriteria: "Daglichteis of gewenste oriëntatie per hoofd-ruimte benoemd.",
    riskOverlay: "Onvoldoende daglicht leidt tot NEN 2057-overschrijding en verminderd wooncomfort.",
    pitfalls: ["'Veel licht' zonder specifieke richtingen", "Uitzichteisen niet vastgelegd", "Schaduwrisico buurperceel niet onderzocht"],
    exampleGood: "Woonkamer georiënteerd op zuidwest (ochtenddunker, middagzon). Slaapkamer 1 op oost voor ochtendlicht.",
  },
  {
    id: "ruimtes.buitenruimte",
    chapter: "ruimtes",
    fieldId: "buitenruimte",
    label: "Buitenruimte",
    severity: "important",
    fixEffort: "S",
    weight: 5,
    keywords: ["tuin", "terras", "balkon", "buitenruimte", "dakterras", "patio", "buitenkeuken", "overkapping"],
    qualityCriteria: "Gewenst type buitenruimte met m² en oriëntatie benoemd.",
    riskOverlay: "Buitenruimte beïnvloedt perceelsbezetting (bebouwingspercentage) en buurrelaties.",
    pitfalls: ["Terrasoppervlak te klein voor gebruik", "Oriëntatie niet afgestemd op zon", "Overkapping zonder vergunningcheck"],
    exampleGood: "Achtertuin minimaal 60m² op zuidwest. Overdekt terras (15m²) direct aansluitend op woonkamer.",
  },
  {
    id: "ruimtes.akoestiek",
    chapter: "ruimtes",
    fieldId: "akoestiek",
    label: "Akoestische eisen",
    severity: "nice_to_have",
    fixEffort: "S",
    weight: 3,
    keywords: ["akoestiek", "geluid", "geluidsoverlast", "isolatie", "stillere", "muziek", "studio", "geluidsisolatie"],
    qualityCriteria: "Specifieke geluidsisolatie-eis of stilte-zone per ruimte benoemd.",
    riskOverlay: "Onvoldoende luchtgeluidsisolatie (< Rw 52 dB) leidt tot geschillen en kostbare aanpassingen achteraf.",
    pitfalls: ["Akoestiek niet benoemd bij thuisstudio of muziekkamer", "Trapgeluid niet meegenomen"],
    exampleGood: "Thuiskantoor vereist luchtgeluidsisolatie ≥ Rw 52 dB t.o.v. woonkamer. Trap met geluiddempende bekleding.",
  },

  // ── WENSEN ────────────────────────────────────────────────────────────────
  {
    id: "wensen.wishes",
    chapter: "wensen",
    fieldId: "wishes",
    label: "Wensen en prioriteiten",
    severity: "critical",
    fixEffort: "M",
    weight: 16,
    keywords: ["must", "nice", "wens", "prioriteit", "belangrijk", "eis", "voorwaarde", "moet"],
    qualityCriteria: "Minimaal 5 wensen met MoSCoW-prioriteit (must/nice/optional).",
    riskOverlay: "Zonder geprioriteerde wensen kan geen afweging worden gemaakt bij budgetdruk.",
    pitfalls: ["Alle wensen als 'must-have'", "Geen onderscheid functioneel/esthetisch", "Wensen zonder meetbaar criterium"],
    exampleGood: "Must: open keuken-woonkamer, vloerverwarming, 3 slaapkamers. Nice: inloopkast, dakraam. Optioneel: buitensauna.",
  },
  {
    id: "wensen.toekomstbestendigheid",
    chapter: "wensen",
    fieldId: "toekomstbestendigheid",
    label: "Toekomstbestendigheid",
    severity: "important",
    fixEffort: "S",
    weight: 5,
    keywords: ["levensloopbestendig", "toekomst", "aanpasbaar", "flexibel", "ouder worden", "rolstoel", "verdeelbaar", "doorgroei"],
    qualityCriteria: "Levensloopbestendigheid of flexibele indeling-eis expliciet benoemd.",
    riskOverlay: "Niet-aanpasbare woningen vereisen kostbare verbouwingen bij veranderende mobiliteit.",
    pitfalls: ["'Flexibel' zonder concrete maat of constructieve consequentie", "Slaapkamer op begane grond vergeten"],
    exampleGood: "Begane grond levensloopbestendig: slaapkamer + natte cel mogelijk zonder trapgebruik. Muren constructiefvrij voor toekomstige doorbraken.",
  },
  {
    id: "wensen.stijl",
    chapter: "wensen",
    fieldId: "stijl",
    label: "Architectuurstijl en sfeer",
    severity: "nice_to_have",
    fixEffort: "XS",
    weight: 3,
    keywords: ["stijl", "sfeer", "modern", "klassiek", "industrieel", "scandinavisch", "materiaal", "kleur", "uitstraling", "esthetisch"],
    qualityCriteria: "Gewenste architectuurstijl of referentie-sfeer benoemd.",
    riskOverlay: "Onduidelijke stijlkeuze leidt tot herhaaldelijke ontwerprondes en tegenstrijdige feedback.",
    pitfalls: ["Alleen 'modern' zonder verdere toelichting", "Tegenstrijdige stijlreferenties (industrieel én klassiek)"],
    exampleGood: "Stijl: warm Scandinavisch — lichte houtstructuren, witte gevels, houten vloeren. Referentie: Rietveld Schröder interieur.",
  },
  {
    id: "wensen.binnenklimaat",
    chapter: "wensen",
    fieldId: "binnenklimaat",
    label: "Binnenklimaat comfort",
    severity: "important",
    fixEffort: "S",
    weight: 4,
    keywords: ["comfort", "temperatuur", "luchtkwaliteit", "co2", "vochtigheid", "thermisch", "oververhitting", "koeling"],
    qualityCriteria: "Thermisch comforteis of luchtkwaliteitseis (CO₂-gehalte, vochtigheid) benoemd.",
    riskOverlay: "Oververhitting (TO-uur overschrijding) en slechte luchtkwaliteit zijn veelste klachten bij nieuwbouw.",
    pitfalls: ["Koeling niet benoemd bij goed geïsoleerde schil", "Zomercomfort vergeten bij grote glazen pui"],
    exampleGood: "Binnentemperatuur max. 25°C op 90% van de zomerdagen. CO₂-gehalte max. 800 ppm in slaapkamers.",
  },

  // ── BUDGET ────────────────────────────────────────────────────────────────
  {
    id: "budget.budgetTotaal",
    chapter: "budget",
    fieldId: "budgetTotaal",
    label: "Budget indicatie",
    severity: "critical",
    fixEffort: "S",
    weight: 16,
    keywords: ["budget", "euro", "kosten", "maximaal", "investering", "begroting", "€"],
    qualityCriteria: "Concreet bedrag of bandbreedte met onder- en bovengrens.",
    riskOverlay: "Zonder budget is geen haalbaarheidstoets mogelijk en dreigt overschrijding.",
    pitfalls: ["'Zo goedkoop mogelijk'", "Budget exclusief BTW/bijkomende kosten", "Financiering niet benoemd"],
    exampleGood: "Het beschikbare bouwbudget is €275.000 – €325.000 inclusief BTW, exclusief grondkosten en leges.",
  },
  {
    id: "budget.bufferpost",
    chapter: "budget",
    fieldId: "bufferpost",
    label: "Risicobudget / onvoorzien",
    severity: "important",
    fixEffort: "XS",
    weight: 6,
    keywords: ["buffer", "onvoorzien", "risico", "reserve", "meerwerk", "tegenvallers", "contingency"],
    qualityCriteria: "Bufferpercentage of absoluut reservebedrag benoemd (aanbevolen: 10-15%).",
    riskOverlay: "Projecten zonder buffer overschrijden budget gemiddeld met 12-18% (bron: Bouwend Nederland).",
    pitfalls: ["Geen buffer opgenomen", "Buffer onder 5% bij verbouwing bestaande bouw", "Buffer verward met wensenpotje"],
    exampleGood: "Reservepost onvoorzien: €30.000 (±10% van bouwsom). Inzetbaar voor meerwerk funderingsonderzoek en directievoering.",
  },
  {
    id: "budget.btwBijkomend",
    chapter: "budget",
    fieldId: "btwBijkomend",
    label: "BTW en bijkomende kosten",
    severity: "important",
    fixEffort: "XS",
    weight: 5,
    keywords: ["btw", "leges", "honorarium", "bijkomend", "notaris", "makelaarskosten", "overdracht", "kosten koper"],
    qualityCriteria: "BTW-regime (21%/9%/0%) en bijkomende kosten (leges, honorarium, notaris) benoemd.",
    riskOverlay: "Bijkomende kosten zijn gemiddeld 15-25% bovenop de bouwsom en worden vaak onderschat.",
    pitfalls: ["Budget exclusief BTW opgegeven", "Architecthonorarium niet meegenomen", "Leges OV-vergunning vergeten"],
    exampleGood: "Budget incl. 21% BTW bouwkosten + 9% BTW renovatie. Bijkomend: €8.000 leges, €25.000 architecthonorarium (DO t/m DA).",
  },
  {
    id: "budget.financiering",
    chapter: "budget",
    fieldId: "financiering",
    label: "Financieringsvorm",
    severity: "nice_to_have",
    fixEffort: "XS",
    weight: 3,
    keywords: ["hypotheek", "financiering", "eigen geld", "lening", "eigenkapitaal", "bouwdepot", "subsidie"],
    qualityCriteria: "Financieringsvorm en eventuele beperkingen (bouwdepot, subsidie) benoemd.",
    riskOverlay: "Bouwdepot-eisen van de bank kunnen meerwerk en planning beïnvloeden.",
    pitfalls: ["Subsidie verwacht zonder check of aanvraag", "Bouwdepot-fasering niet afgestemd op aannemer"],
    exampleGood: "Financiering via hypotheek met bouwdepot (€50.000). Eigen kapitaal: €80.000. Subsidie ISDE warmtepomp aangevraagd.",
  },

  // ── TECHNIEK ──────────────────────────────────────────────────────────────
  {
    id: "techniek.verwarming",
    chapter: "techniek",
    fieldId: "verwarming",
    label: "Verwarmingssysteem",
    severity: "critical",
    fixEffort: "S",
    weight: 10,
    keywords: ["warmtepomp", "verwarming", "cv", "vloerverwarming", "radiatoren", "all-electric", "gas"],
    qualityCriteria: "Gekozen verwarmingssysteem + afgiftetype benoemd.",
    riskOverlay: "Verwarmingskeuze bepaalt netaansluiting, vloerhoogte en exploitatiekosten.",
    pitfalls: ["'Duurzaam verwarmen' zonder concreet systeem", "Hybride vs. all-electric niet gekozen"],
    exampleGood: "All-electric warmtepomp (lucht-water) met lage-temperatuur vloerverwarming op begane grond en radiatoren op verdieping.",
  },
  {
    id: "techniek.ventilatie",
    chapter: "techniek",
    fieldId: "ventilatie",
    label: "Ventilatiesysteem",
    severity: "important",
    fixEffort: "S",
    weight: 6,
    keywords: ["ventilatie", "wtw", "mechanisch", "natuurlijk", "lucht", "afzuiging"],
    qualityCriteria: "Ventilatieconcept benoemd (natuurlijk/mechanisch/balans-WTW).",
    riskOverlay: "Ventilatie bepaalt leidingvoering, plafondhoogte en binnenluchtkwaliteit.",
    pitfalls: ["Ventilatie niet benoemd bij goed geïsoleerde schil", "WTW zonder kanaalvoering"],
    exampleGood: "Balansventilatie met WTW (rendement ≥90%), centrale unit op zolder, toevoer via plafondrooster.",
  },
  {
    id: "techniek.isolatie",
    chapter: "techniek",
    fieldId: "isolatie",
    label: "Isolatie / schil",
    severity: "important",
    fixEffort: "S",
    weight: 6,
    keywords: ["isolatie", "rc-waarde", "schil", "spouw", "dak", "vloer", "gevel"],
    qualityCriteria: "Isolatie-ambitie of Rc-waarden per bouwdeel benoemd.",
    riskOverlay: "Isolatiekeuze bepaalt energielabel, comfort en verwarmingscapaciteit.",
    pitfalls: ["'Goed geïsoleerd' zonder Rc-waarden", "Vloerisolatie vergeten bij bestaande bouw"],
    exampleGood: "Gevel Rc ≥ 4.5, dak Rc ≥ 6.0, vloer Rc ≥ 3.5, HR++ beglazing (U ≤ 1.1).",
  },
  {
    id: "techniek.daglichtGlas",
    chapter: "techniek",
    fieldId: "daglichtGlas",
    label: "Glaspercentage en zonwering",
    severity: "important",
    fixEffort: "S",
    weight: 5,
    keywords: ["glas", "glaspercentage", "daglicht", "zonwering", "hor", "screen", "pui", "beglazing"],
    qualityCriteria: "Glaspercentage per gevel of type beglazing + gewenste zonweringstrategie benoemd.",
    riskOverlay: "Te groot glasoppervlak zonder zonwering leidt tot oververhitting (TO > 450°Ch).",
    pitfalls: ["Grote puien zonder zonweringsstrategie", "Triple glass vs. HR++ niet afgewogen", "Glaspercentage boven 30% zonder koelingsstrategie"],
    exampleGood: "Zuidgevel 25% glas met uitwendige screen (Fc ≤ 0.20). Noordgevel 15% glas voor daglicht, geen directe zon.",
  },
  {
    id: "techniek.sanitair",
    chapter: "techniek",
    fieldId: "sanitair",
    label: "Sanitaire installatie",
    severity: "important",
    fixEffort: "S",
    weight: 5,
    keywords: ["sanitair", "douche", "bad", "toilet", "kraan", "warmwater", "boiler", "tapwater", "badkamer"],
    qualityCriteria: "Sanitaire eisen per ruimte (bad/douche-combinatie, 2e toilet, etc.) en warmwatersysteem benoemd.",
    riskOverlay: "Sanitaire herindeling achteraf is een van de duurste aanpassingen in bestaande bouw.",
    pitfalls: ["Badkamer op verdieping zonder aandacht voor leidingvoering begane grond", "Warmwatercapaciteit voor meerdere taps niet berekend"],
    exampleGood: "Badkamer incl. inloopdouche (90×120) + ligbad + dubbele wastafel. Separaat toilet op elke woonlaag. Warmwater via boilervat 200L.",
  },
  {
    id: "techniek.elektra",
    chapter: "techniek",
    fieldId: "elektra",
    label: "Elektra en domotica",
    severity: "nice_to_have",
    fixEffort: "S",
    weight: 3,
    keywords: ["elektra", "laadpaal", "ev", "domotica", "smart home", "groepenkast", "3x25a", "aansluiting", "thuisbatterij"],
    qualityCriteria: "Gewenst aansluitvermogen, laadpaal en domotica-wensen benoemd.",
    riskOverlay: "Onvoldoende netaansluiting blokkeert laadpaal en warmtepomp; netcongestie verlengt aansluitingstijd.",
    pitfalls: ["3x25A aansluiting bij all-electric + EV te krap", "Domotica-infrastructuur (leidingen) niet in bouwfase meenemen"],
    exampleGood: "Aansluiting 3×40A. Laadpaal (11 kW) in garage. Domotica-infrastructuur (lege buizen + centraal punt) voor toekomstbestendigheid.",
  },
  {
    id: "techniek.bouwfysica",
    chapter: "techniek",
    fieldId: "bouwfysica",
    label: "Bouwfysica en vocht",
    severity: "important",
    fixEffort: "S",
    weight: 5,
    keywords: ["vocht", "condensatie", "koudebruggen", "dampscherm", "luchtdichtheid", "schimmel", "blower door"],
    qualityCriteria: "Luchtdichtheidseis (qv10) en koudebrugaanpak benoemd, met name bij renovatie.",
    riskOverlay: "Onvoldoende luchtdichtheid en koudebruggen zijn oorzaak van 60% van de vochtklachten.",
    pitfalls: ["Renovatie zonder thermografisch onderzoek", "Nieuwe isolatielaag zonder dampscherm-detaillering", "Blower door-test niet gepland"],
    exampleGood: "Luchtdichtheidsdoelstelling: qv10 ≤ 0.4 dm³/s·m². Blower door-test na dicht gemaakte schil. Koudebrugvrij detail bij vloer-gevel-aansluiting.",
  },

  // ── DUURZAAM ──────────────────────────────────────────────────────────────
  {
    id: "duurzaam.energieLabel",
    chapter: "duurzaam",
    fieldId: "energieLabel",
    label: "Energiedoelstelling",
    severity: "important",
    fixEffort: "S",
    weight: 8,
    keywords: ["energielabel", "duurzaam", "nul-op-de-meter", "epc", "beng", "gasloos", "zonnepanelen"],
    qualityCriteria: "Concreet energielabel-doel of BENG-eis benoemd.",
    riskOverlay: "Energiedoel bepaalt schilkwaliteit, installatiekeuze en terugverdientijd.",
    pitfalls: ["'Zo duurzaam mogelijk' zonder meetbaar doel", "Label A++ vs. NOM verward"],
    exampleGood: "Streefniveau: energielabel A++, BENG 1 ≤ 50 kWh/m²/jaar, gasloze exploitatie.",
  },
  {
    id: "duurzaam.zonnepanelen",
    chapter: "duurzaam",
    fieldId: "zonnepanelen",
    label: "Zonnepanelen / opwek",
    severity: "nice_to_have",
    fixEffort: "XS",
    weight: 4,
    keywords: ["zonnepanelen", "pv", "opwek", "zonne-energie", "omvormer"],
    qualityCriteria: "Aantal panelen of Wp-vermogen + oriëntatie benoemd.",
    riskOverlay: "PV-installatie beïnvloedt dakconstructie en netaansluiting.",
    pitfalls: ["Alleen 'zonnepanelen' zonder capaciteit", "Oriëntatie niet gecheckt"],
    exampleGood: "16 zonnepanelen (±6.4 kWp) op zuidwest-georiënteerd dak (hellingshoek 35°).",
  },
  {
    id: "duurzaam.materialen",
    chapter: "duurzaam",
    fieldId: "materialen",
    label: "Materialen en circulariteit",
    severity: "nice_to_have",
    fixEffort: "S",
    weight: 3,
    keywords: ["biobased", "hout", "circulair", "hergebruik", "milieu", "mpg", "productpaspoort", "FSC", "duurzaam materiaal"],
    qualityCriteria: "Materiaalkeuze-ambitie (biobased, circulair, MPG-score) benoemd.",
    riskOverlay: "Hogere duurzaamheidsambities voor materialen verhogen bouwkosten met 5-15% als dit niet vroeg in het budget is opgenomen.",
    pitfalls: ["'Duurzame materialen' zonder MPG-doel of specificatie", "Biobased isolatie niet afgestemd op brandklasse-eis"],
    exampleGood: "MPG ≤ 0.8. Voorkeur biobased isolatie (houtvezel). Houten constructie FSC-gecertificeerd. Materiaallijst met productpaspoorten.",
  },
  {
    id: "duurzaam.water",
    chapter: "duurzaam",
    fieldId: "watergebruik",
    label: "Watergebruik en opvang",
    severity: "nice_to_have",
    fixEffort: "S",
    weight: 3,
    keywords: ["regenwater", "grijswater", "regenton", "wateropvang", "waterbesparend", "droogtebestendig", "infiltratie"],
    qualityCriteria: "Regenwateropvang, grijswaterhergebruik of infiltratiestrategie benoemd.",
    riskOverlay: "Ongeremd afvoer van regenwater leidt bij extreme buien tot wateroverlast en riooloverbelasting.",
    pitfalls: ["Verhard oppervlak vergroot zonder compensatiemaatregel", "Regentonnen te klein voor dakoppervlak"],
    exampleGood: "Regenwateropvang: 3.000L ondergrondse tank voor toiletspoeling en tuinberegening. Groendak op bijgebouw (80m²) vertraagt afvoer.",
  },

  // ── RISICO ────────────────────────────────────────────────────────────────
  {
    id: "risico.planning",
    chapter: "risico",
    fieldId: "risks",
    label: "Planning en doorlooptijd",
    severity: "important",
    fixEffort: "S",
    weight: 6,
    keywords: ["planning", "doorlooptijd", "oplevering", "start", "deadline", "maanden", "weken"],
    qualityCriteria: "Gewenste start- en opleverdatum of doorlooptijd benoemd.",
    riskOverlay: "Zonder planning is vergunnings- en uitvoeringstijd niet te toetsen.",
    pitfalls: ["'Zo snel mogelijk' zonder realistische doorlooptijd", "Vergunningsdoorlooptijd niet meegenomen"],
    exampleGood: "Gewenste start bouw: september 2026, oplevering: maart 2027 (6 maanden doorlooptijd).",
  },
  {
    id: "risico.vergunning",
    chapter: "risico",
    fieldId: "risks",
    label: "Vergunningsstatus",
    severity: "important",
    fixEffort: "XS",
    weight: 4,
    keywords: ["vergunning", "omgevingsvergunning", "bouwvergunning", "bestemmingsplan", "welstand"],
    qualityCriteria: "Vergunningsplicht en status (aangevraagd/verleend/onbekend) benoemd.",
    riskOverlay: "Ontbrekende vergunning kan het gehele project stilleggen.",
    pitfalls: ["Aanname 'vergunningvrij' zonder toetsing", "Welstandscommissie niet meegenomen"],
    exampleGood: "Omgevingsvergunning is vereist en wordt aangevraagd na definitief ontwerp. Bestemmingsplan laat de uitbouw toe.",
  },
  {
    id: "risico.scope",
    chapter: "risico",
    fieldId: "risks",
    label: "Scope en verantwoordelijkheden",
    severity: "nice_to_have",
    fixEffort: "M",
    weight: 4,
    keywords: ["scope", "verantwoordelijkheid", "aannemer", "architect", "opdrachtgever", "wie doet wat"],
    qualityCriteria: "Rolverdeling opdrachtgever/architect/aannemer + scope-afbakening benoemd.",
    riskOverlay: "Onduidelijke scope leidt tot meerwerk-discussies en vertraging.",
    pitfalls: ["Geen onderscheid casco vs. turn-key", "Zelfwerkzaamheid niet afgebakend"],
    exampleGood: "Opdrachtgever regelt schilderwerk en tuin. Aannemer levert casco+ (incl. keuken, sanitair). Architect bewaakt kwaliteit.",
  },
  {
    id: "risico.constructief",
    chapter: "risico",
    fieldId: "risks",
    label: "Constructieve risico's",
    severity: "important",
    fixEffort: "M",
    weight: 5,
    keywords: ["fundering", "constructie", "dragende muur", "doorbraak", "fundering", "zetting", "palen", "beton", "staal"],
    qualityCriteria: "Constructieve maatregelen bij verbouwing (funderingsstaat, dragende elementen) benoemd of onderzocht.",
    riskOverlay: "Onverwachte funderingsproblemen zijn gemiddeld €15.000-€40.000 meerkosten.",
    pitfalls: ["Open keuken met dragende muur niet gecheckt", "Funderingsinspectie overgeslagen bij pre-1940 bouw", "Zettingsverschil uitbouw vs. bestaand niet meegenomen"],
    exampleGood: "Funderingsinspectie uitgevoerd (rapport bijgevoegd). Doorbraak begane grond vereist staalconstructie — opgenomen in aanbestedingsscope.",
  },
  {
    id: "risico.asbest",
    chapter: "risico",
    fieldId: "risks",
    label: "Asbestrisico",
    severity: "important",
    fixEffort: "S",
    weight: 4,
    keywords: ["asbest", "asbestinventarisatie", "asbestsanering", "pre-1994", "golfplaten", "vloerbedekking", "textiel"],
    qualityCriteria: "Asbestinventarisatie uitgevoerd of aantoonbaar niet van toepassing (bouwjaar > 1994).",
    riskOverlay: "Asbestsanering zonder inventarisatie is strafbaar. Kosten lopen op tot €50.000+ bij onderschatting.",
    pitfalls: ["Bouwjaar < 1994 zonder asbestcheck", "Scope 'sloop dakplaten' zonder inventarisatie", "Inventarisatie verward met sanering"],
    exampleGood: "Type A asbestinventarisatie uitgevoerd (rapport 2025). Dakgoten en vloerbedekking zijn asbestvrij. Saneringskosten €0.",
  },
  {
    id: "risico.omgeving",
    chapter: "risico",
    fieldId: "risks",
    label: "Omgevingshinder en logistiek",
    severity: "nice_to_have",
    fixEffort: "S",
    weight: 3,
    keywords: ["buren", "overlast", "bereikbaarheid", "kraanwagen", "buurt", "omgeving", "hinder", "bouwverkeer"],
    qualityCriteria: "Omgevingsfactoren zoals buurrelaties, bereikbaarheid bouwverkeer en tijdelijke bewoning benoemd.",
    riskOverlay: "Kraanopstelling bij smalle straat of buren-protest kunnen start bouwen weken vertragen.",
    pitfalls: ["Kraanopstelling in smalle straat niet gecheckt", "Tijdelijke verhuizing niet in budget opgenomen", "Buren niet geïnformeerd → bezwaar"],
    exampleGood: "Buren geïnformeerd (akkoord ondertekend). Kraan op openbaar terrein: ontheffing gemeente aangevraagd. Tijdelijk verblijf budget: €3.000.",
  },
];

// ============================================================================
// EXPORT
// ============================================================================

export const PVE_RUBRIC: PveRubric = {
  version: RUBRIC_VERSION,
  items: ITEMS,
};

export function getRubricVersion(): string {
  return PVE_RUBRIC.version;
}

/** Lookup a single rubric item by id */
export function getRubricItem(id: string): PveRubricItem | undefined {
  return ITEMS.find((item) => item.id === id);
}

/** All field IDs in the rubric (whitelist) */
export function getRubricFieldIds(): string[] {
  return ITEMS.map((item) => item.fieldId);
}
